server:
  port: 9002
  servlet:
    context-path: /client02
#OAuth2.0配置
security:
  oauth2:
    client:
      clientId: ht17520
      clientSecret: ht17520
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key