server:
  port: 7001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  session:
    store-type: none
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.xh.demo.domain.po
  configuration:
    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
mapper:
  mappers: com.xh.demo.dao.base.IBaseMapper
  notEmpty: false
  identity: MYSQL
logging:
  level:
    com.xh.demo.dao.mapper: debug
#配置OAuth2.0登录认证信息
xh:
  security:
    oauth2:
      siteDomain: http://ih27ua.natappfree.cc
      gitee:
        clientId: 4b8901f6a1942bc4da2f5e439b6412158eff55719f60808f9d7065ee44a103e4
        clientSecret: f56c7e6666d52b30f8e816bbe09a37df5b47485f0d9a7a851aa5fd9df44b41f0